name: Auto Formatting

on: push

jobs:
  auto-formatting:
    name: Auto Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup Python 3.8.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5
          architecture: x64
          cache: pip

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install autoflake black isort

      - name: Run autoflake
        run: autoflake -r .

      - name: Run black
        run: black .

      - name: Run isort
        run: isort .

      - name: Get diff on Auto-formatting
        id: formatting_diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit formatting codes
        if: steps.formatting_diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m '[Actions] Code Formatting'
          git push