name: Auto formatting

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  auto-formatting:
    name: Auto Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python 3.8.5
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8.5
          architecture: x64
          cache: pip

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install autoflake black isort

      - name: Run autoflake
        run: autoflake -r .

      - name: Run black
        run: black .

      - name: Get auto-formatting diff
        id: formatting_diff
        continue-on-error: true
        run: |
          git add -N .
          git diff --exit-code
          echo "exit: ${$?}"

      - name: Commit formatting codes
        if: steps.formatting_diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m '[Actions] Code Formatting'
          git push