name: Auto Formatting

on: push

jobs:
  auto-formatting:
    name: Auto Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup Python 3.8.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5
          architecture: x64
          cache: pip

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install autoflake black isort

      - name: Run autoflake
        run: autoflake -r .

      - name: Run black
        run: black .

      - name: Run isort
        run: isort .

      - name: Commit formatting codes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: [Actions] Code Formatting