name: Check Syntax

on: push

jobs:
  check-syntax:
    name: Check Syntax
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup Python 3.8.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5
          architecture: x64
          cache: pip

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --select=E9,F63,F72,F82