name: Check Syntax

on: push

jobs:
  check-syntax:
    name: Check Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture: x64

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --select=E9,F63,F72,F82
